#!/bin/sh

PATH=$PATH:`dirname $0`

for fname in "$@"
do
	vtab2ly $fname | lilypond \
		-dbackend=svg \
		-o `dirname $fname`/`basename $fname .vtab` \
		-

	# It would be better to find a non-X11 tool to do this.
	inkscape \
		--verb=FitCanvasToDrawing \
		--verb=FileSave \
		--verb=FileQuit \
		`dirname $fname`/`basename $fname .vtab`.svg
done
