#!/usr/bin/env python

import sys
import vtab.dummy_formatter
import vtab.vtab_parser

f = vtab.dummy_formatter.DummyFormatter()
p = vtab.vtab_parser.VtabParser()
p.add_formatter(f)

if 0 != len(sys.argv):
	for fname in sys.argv:
		f = open(fname)
		p.parse_file(f)
		f.close()
else:
	p.parse_file(sys.stdin)
