#!/usr/bin/env python

import sys
import vtab.dummy_formatter
import vtab.vtab_parser

f = vtab.dummy_formatter.DummyFormatter()
p = vtab.vtab_parser.VtabParser()
p.add_formatter(f)

for ln in sys.stdin.readlines():
	ln = ln.rstrip()
	p.parse(ln)
