#!/usr/bin/env python

import sys
import vtab

f = vtab.LilypondFormatter()
p = vtab.VtabParser()
p.add_formatter(f)

if len(sys.argv) >= 2:
	for fname in sys.argv[1:]:
		f = open(fname)
		p.parse_file(f)
		f.close()
else:
	p.parse_file(sys.stdin)
